name: CI
on:
  push:
    branches:
      - main
    paths-ignore: 
      - README.md
      - LICENSE
      - .github/*
      - .gitattributes
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: MissdropServer/Vuepress-deploy
          TARGET_BRANCH: main
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
          COMMIT_MESSAGE: Auto Deploy Success
          #CNAME: bakaxl.ml